#!/bin/bash

echo "################################################################"
echo "# Tmux Info"
echo "################################################################"
echo "# "
echo "# Prefix + I = Install plugins and reload Tmux config"
echo "# "
echo "################################################################"
echo "# Windows"
echo "# "
echo "# Prefix + c = Create Window"
echo "# Prefix + n = Move to next window"
echo "# Prefix + p = Move to previous window"
echo "# Prefix + & = Kill Window"
echo "# Prefix + , = Rename Window"
echo "# "
echo "################################################################"
echo "# Panes"
echo "# "
echo "# Prefix + % = Split vertically"
echo '# Prefix + " = Split horizontally'
echo "# Prefix + <Arrow Key> = Move to pane in that direction"
echo "# Prefix + ! = Convert Pane to window"
echo "# Prefix + X = Kill Pane"
echo "# "
echo "################################################################"
echo "# Logging"
echo "# "
echo "# Prefix + P = Start/Stop Logging"
echo "# Prefix + <alt> + p = Screen Capture"
echo "# Prefix + <alt> + P = Save Complete History"
echo "# "
echo "################################################################"
echo "# Yank"
echo "# "
echo "# Prefix + y = Copy command line to clipboard"
echo "# Prefix + Y = Copy current working directory to clipboard"
echo "# "
echo "# Copy Mode:"
echo "# y = Copy selection to clipboard"
echo "# Y = Copy selection and paste to command line"
echo "# "
echo "# "
echo "# Prefix + ? = List all key bindings"
echo "################################################################"
